from primelock_gis.core.geometry import Point
from primelock_gis.core.rendering.viewport import Viewport
from primelock_gis.core.rendering.scene import DrawablePoint, DrawablePolyline, Scene
from primelock_gis.core.rendering.symbology import PointStyle, PolylineStyle
from primelock_gis.ui.terminal.canvas import TerminalCanvas
from primelock_gis.ui.terminal.capabilities import TerminalCapabilities
from primelock_gis.ui.terminal.renderer2d import TerminalRenderer2D

""" Tests generated by an LLM after asking it to gnerate tests for:
- renderer clear resets canvas
- draw_point draws style character
- render_scene draws visible point
- render_scene skips invisible point
- point outside viewport does not crash
"""

def make_renderer():
    canvas = TerminalCanvas(10, 10, ".")
    viewport = Viewport(
        world_min_x=0,
        world_min_y=0,
        world_max_x=100,
        world_max_y=100,
        view_width=10,
        view_height=10,
    )
    capabilities = TerminalCapabilities()
    return TerminalRenderer2D(canvas, viewport, capabilities)


def test_renderer_clear_resets_canvas():
    renderer = make_renderer()

    renderer.canvas.set_cell(5, 5, "X")
    renderer.clear()

    assert renderer.to_string() == "\n".join(["." * 10 for _ in range(10)])


def test_draw_point_draws_style_character():
    renderer = make_renderer()
    point = DrawablePoint(
        position=Point(50, 50),
        style=PointStyle(char="●"),
    )

    renderer.draw_point(point)

    rows = renderer.to_string().split("\n")
    assert rows[5][5] == "●"


def test_render_scene_draws_visible_point():
    renderer = make_renderer()
    scene = Scene()

    scene.points.append(
        DrawablePoint(
            position=Point(50, 50),
            style=PointStyle(char="●"),
            visible=True,
        )
    )

    renderer.render_scene(scene)

    rows = renderer.to_string().split("\n")
    assert rows[5][5] == "●"


def test_render_scene_skips_invisible_point():
    renderer = make_renderer()
    scene = Scene()

    scene.points.append(
        DrawablePoint(
            position=Point(50, 50),
            style=PointStyle(char="●"),
            visible=False,
        )
    )

    renderer.render_scene(scene)

    assert "●" not in renderer.to_string()


def test_point_outside_viewport_does_not_crash():
    renderer = make_renderer()
    point = DrawablePoint(
        position=Point(999, 999),
        style=PointStyle(char="●"),
    )

    renderer.draw_point(point)

    assert isinstance(renderer.to_string(), str)


def test_draw_horizontal_polyline():
    renderer = make_renderer()
    line = DrawablePolyline(
        points=[Point(10, 50), Point(90, 50)],
        style=PolylineStyle(char="-"),
    )

    renderer.draw_polyline(line)

    output = renderer.to_string()
    assert "-" in output


def test_draw_diagonal_polyline():
    renderer = make_renderer()
    line = DrawablePolyline(
        points=[Point(10, 10), Point(90, 50)],
        style=PolylineStyle(char="-"),
    )

    renderer.draw_polyline(line)

    output = renderer.to_string()
    assert "-" in output